name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg-cache
  VCPKG_ROOT: C:\vcpkg

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup MSVC environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Setup vcpkg
      run: |
        mkdir -p ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}
        cd $env:VCPKG_INSTALLATION_ROOT
        ./bootstrap-vcpkg.bat
        ./vcpkg --version > ${{ github.workspace }}/vcpkg-version.txt

    - name: Cache vcpkg
      uses: actions/cache@v4
      id: vcpkg-cache
      with:
        path: ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}/*
        key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json', 'vcpkg-version.txt') }}

    - name: Configure CMake
      run: cmake --preset build-release-msvc

    - name: Build
      run: cmake --build --preset release-msvc

    - name: Install
      run: |
        cmake --install ${{ github.workspace }}/build/release-msvc --component "components" --prefix ${{ github.workspace }}/ReleaseBuild
        cmake --install ${{ github.workspace }}/build/release-msvc --component "SKSEPlugin" --prefix ${{ github.workspace }}/ReleaseBuild

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ConsiderateFollowers-AE
        path: ${{ github.workspace }}/ReleaseBuild
